// ERZEUGT VON scripts/druck_swift.py. NICHT VON HAND ÄNDERN.
//
// Die Quelle ist backend/designer/druck.py. Was hier steht, hat der
// SERVER gerechnet: Aus dieser Wahl wird genau diese Adresse und genau
// dieser Dateiname.
//
// Die wunden Punkte stehen absichtlich mitten drin: eine Kartenzahl, die
// es nicht gibt (sie wird 4), zwanzig Einlagen auf einem Bogen (es
// werden 12), ein Armband von einem Millimeter (es wird die kleinste
// erlaubte Breite) und ein frei getipptes Mass, das zufällig genau der
// Jugendgröße entspricht (es heißt dann „Jugend" und nicht „Eigenes
// Maß"). Alle vier ergeben einen Ausdruck, der niemandem falsch
// vorkommt. Er ist nur nicht der bestellte.
//
// Neu erzeugen:  ./scripts/druck_swift.py
// Geprüft von:   backend/designer/test_druck_swift.py (Gleichstand)
//                RoutetreeTests/DruckTests.swift (Swift rechnet gleich)

import Foundation

enum DruckProben {

    /// Eine vollständige Wahl und das, was der Server daraus macht.
    struct Fall {
        let art: String
        let proSeite: Int
        let spalten: Int
        let groesse: String
        let breite: Double
        let hoehe: Double
        let kopien: Int
        let stil: String
        /// Wie viele Plays auf eine Einlage kommen (R74). 0 = alle.
        let jeEinlage: Int
        let anordnung: String
        /// Was unter dem Diagramm einer Playcard steht (R74).
        let kartenfuss: String
        /// Wie viele Plays je Situationsblock aufs Call Sheet. 0 = alle.
        let jeBlock: Int
        let diagramme: Bool
        let zoom: String
        let zeichenstil: String
        let bildbreite: Double
        let logo: Bool
        let sw: Bool
        let seite: String
        /// Die Adresse, die der Server für diese Wahl baut.
        let adresse: String
        /// Und wie die Datei danach heißt.
        let dateiname: String
    }

    /// Die Kennung, mit der die Adressen oben gebaut sind.
    static let kennung = 7
    /// Der schon bereinigte Name, aus dem die Dateinamen entstehen.
    static let stamm = "u17-heimspiel"

    static let faelle: [Fall] = [
        Fall(art: "playcards",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/playcards/?pro_seite=4&kartenfuss=situationen&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-playcards.pdf"),
        Fall(art: "playcards",
             proSeite: 9, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: false, sw: true, seite: "off",
             adresse: "/api/v1/playbooks/7/druck/playcards/?pro_seite=9&kartenfuss=situationen&zoom=normal&zeichenstil=normal&logo=0&sw=1&seite=off",
             dateiname: "u17-heimspiel-playcards.pdf"),
        Fall(art: "playcards",
             proSeite: 7, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/playcards/?pro_seite=4&kartenfuss=situationen&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-playcards.pdf"),
        Fall(art: "playcards",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "notizen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/playcards/?pro_seite=4&kartenfuss=notizen&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-playcards.pdf"),
        Fall(art: "playcards",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "gedicht",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/playcards/?pro_seite=4&kartenfuss=situationen&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-playcards.pdf"),
        Fall(art: "callsheet",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/callsheet/?spalten=3&je_block=0&diagramme=0&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-callsheet.pdf"),
        Fall(art: "callsheet",
             proSeite: 4, spalten: 4,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "def",
             adresse: "/api/v1/playbooks/7/druck/callsheet/?spalten=4&je_block=0&diagramme=0&zoom=normal&zeichenstil=normal&logo=1&sw=0&seite=def",
             dateiname: "u17-heimspiel-callsheet.pdf"),
        Fall(art: "callsheet",
             proSeite: 4, spalten: 5,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/callsheet/?spalten=3&je_block=0&diagramme=0&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-callsheet.pdf"),
        Fall(art: "wristband",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/wristband/?groesse=standard&je_einlage=8&anordnung=raster&kopien=4&stil=diagramm&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-wristband.pdf"),
        Fall(art: "wristband",
             proSeite: 4, spalten: 3,
             groesse: "jugend", breite: 125.0, hoehe: 75.0,
             kopien: 12, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/wristband/?groesse=jugend&je_einlage=8&anordnung=raster&kopien=12&stil=diagramm&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-wristband.pdf"),
        Fall(art: "wristband",
             proSeite: 4, spalten: 3,
             groesse: "riesig", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/wristband/?groesse=standard&je_einlage=8&anordnung=raster&kopien=4&stil=diagramm&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-wristband.pdf"),
        Fall(art: "wristband",
             proSeite: 4, spalten: 3,
             groesse: "frei", breite: 110.0, hoehe: 64.5,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/wristband/?breite=110&hoehe=64.5&je_einlage=8&anordnung=raster&kopien=4&stil=diagramm&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-wristband.pdf"),
        Fall(art: "wristband",
             proSeite: 4, spalten: 3,
             groesse: "frei", breite: 95.0, hoehe: 60.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/wristband/?breite=95&hoehe=60&je_einlage=8&anordnung=raster&kopien=4&stil=diagramm&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-wristband.pdf"),
        Fall(art: "wristband",
             proSeite: 4, spalten: 3,
             groesse: "frei", breite: 1.0, hoehe: 9999.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/wristband/?breite=40&hoehe=260&je_einlage=8&anordnung=raster&kopien=4&stil=diagramm&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-wristband.pdf"),
        Fall(art: "wristband",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 20, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/wristband/?groesse=standard&je_einlage=8&anordnung=raster&kopien=12&stil=diagramm&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-wristband.pdf"),
        Fall(art: "wristband",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 0, stil: "bunt",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/wristband/?groesse=standard&je_einlage=8&anordnung=raster&kopien=1&stil=diagramm&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-wristband.pdf"),
        Fall(art: "wristband",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 0, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/wristband/?groesse=standard&je_einlage=0&anordnung=raster&kopien=4&stil=diagramm&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-wristband.pdf"),
        Fall(art: "wristband",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 4, anordnung: "spalte",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/wristband/?groesse=standard&je_einlage=4&anordnung=spalte&kopien=4&stil=diagramm&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-wristband.pdf"),
        Fall(art: "wristband",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 15, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/wristband/?groesse=standard&je_einlage=15&anordnung=raster&kopien=4&stil=diagramm&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-wristband.pdf"),
        Fall(art: "wristband",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 7, anordnung: "wirbel",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/wristband/?groesse=standard&je_einlage=8&anordnung=raster&kopien=4&stil=diagramm&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-wristband.pdf"),
        Fall(art: "playcards",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "eng", zeichenstil: "kraeftig",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/playcards/?pro_seite=4&kartenfuss=situationen&zoom=eng&zeichenstil=kraeftig&logo=1&sw=0",
             dateiname: "u17-heimspiel-playcards.pdf"),
        Fall(art: "callsheet",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "weit", zeichenstil: "fein",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/callsheet/?spalten=3&je_block=0&diagramme=0&zoom=weit&zeichenstil=fein&logo=1&sw=0",
             dateiname: "u17-heimspiel-callsheet.pdf"),
        Fall(art: "callsheet",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 5, diagramme: true,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/callsheet/?spalten=3&je_block=5&diagramme=1&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-callsheet.pdf"),
        Fall(art: "callsheet",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 7, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/callsheet/?spalten=3&je_block=0&diagramme=0&zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-callsheet.pdf"),
        Fall(art: "wristband",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "eng", zeichenstil: "quietschbunt",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/wristband/?groesse=standard&je_einlage=8&anordnung=raster&kopien=4&stil=diagramm&zoom=eng&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel-wristband.pdf"),
        Fall(art: "bilder",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/bilder/?breite=180&zoom=normal&zeichenstil=normal&sw=0",
             dateiname: "u17-heimspiel-bilder.zip"),
        Fall(art: "bilder",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 300.0,
             logo: true, sw: true, seite: "st",
             adresse: "/api/v1/playbooks/7/druck/bilder/?breite=300&zoom=normal&zeichenstil=normal&sw=1&seite=st",
             dateiname: "u17-heimspiel-bilder.zip"),
        Fall(art: "bilder",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 0.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/playbooks/7/druck/bilder/?breite=40&zoom=normal&zeichenstil=normal&sw=0",
             dateiname: "u17-heimspiel-bilder.zip"),
        Fall(art: "blatt",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/plays/7/druck/blatt/?zoom=normal&zeichenstil=normal&logo=1&sw=0",
             dateiname: "u17-heimspiel.pdf"),
        Fall(art: "blatt",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: false, sw: true, seite: "",
             adresse: "/api/v1/plays/7/druck/blatt/?zoom=normal&zeichenstil=normal&logo=0&sw=1",
             dateiname: "u17-heimspiel.pdf"),
        Fall(art: "bild",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 180.0,
             logo: true, sw: false, seite: "",
             adresse: "/api/v1/plays/7/druck/bild/?breite=180&zoom=normal&zeichenstil=normal&sw=0",
             dateiname: "u17-heimspiel.svg"),
        Fall(art: "bild",
             proSeite: 4, spalten: 3,
             groesse: "standard", breite: 125.0, hoehe: 75.0,
             kopien: 4, stil: "diagramm",
             jeEinlage: 8, anordnung: "raster",
             kartenfuss: "situationen",
             jeBlock: 0, diagramme: false,
             zoom: "normal", zeichenstil: "normal",
             bildbreite: 120.0,
             logo: true, sw: true, seite: "",
             adresse: "/api/v1/plays/7/druck/bild/?breite=120&zoom=normal&zeichenstil=normal&sw=1",
             dateiname: "u17-heimspiel.svg"),
    ]

    /// Größenwahl und freie Eingabe, aufgelöst zu einem Mass.
    struct Mass {
        /// Die gewählte Größe. Leer heißt „keine genannt".
        let groesse: String
        /// Frei getippte Werte. `nil` heißt „nicht getippt" und
        /// ausdrücklich nicht „null Millimeter".
        let breite: Double?
        let hoehe: Double?
        let istBreite: Double
        let istHoehe: Double
        let istGroesse: String
        let label: String
    }

    static let masse: [Mass] = [
        Mass(groesse: "", breite: nil, hoehe: nil,
             istBreite: 125.0, istHoehe: 75.0,
             istGroesse: "standard", label: "Standard (Fenster 127 × 70 mm)"),
        Mass(groesse: "jugend", breite: nil, hoehe: nil,
             istBreite: 95.0, istHoehe: 60.0,
             istGroesse: "jugend", label: "Jugend (Fenster 95 × 57 mm)"),
        Mass(groesse: "gross", breite: nil, hoehe: nil,
             istBreite: 133.0, istHoehe: 83.0,
             istGroesse: "gross", label: "Groß (Fenster 133 × 83 mm)"),
        Mass(groesse: "riesig", breite: nil, hoehe: nil,
             istBreite: 125.0, istHoehe: 75.0,
             istGroesse: "standard", label: "Standard (Fenster 127 × 70 mm)"),
        Mass(groesse: "frei", breite: nil, hoehe: nil,
             istBreite: 125.0, istHoehe: 75.0,
             istGroesse: "standard", label: "Standard (Fenster 127 × 70 mm)"),
        Mass(groesse: "jugend", breite: 110.0, hoehe: nil,
             istBreite: 110.0, istHoehe: 60.0,
             istGroesse: "frei", label: "Eigenes Maß"),
        Mass(groesse: "", breite: 95.0, hoehe: 60.0,
             istBreite: 95.0, istHoehe: 60.0,
             istGroesse: "jugend", label: "Jugend (Fenster 95 × 57 mm)"),
        Mass(groesse: "", breite: 1.0, hoehe: 9999.0,
             istBreite: 40.0, istHoehe: 260.0,
             istGroesse: "frei", label: "Eigenes Maß"),
        Mass(groesse: "", breite: 400.0, hoehe: 10.0,
             istBreite: 190.0, istHoehe: 30.0,
             istGroesse: "frei", label: "Eigenes Maß"),
        Mass(groesse: "", breite: 110.5, hoehe: 64.5,
             istBreite: 110.5, istHoehe: 64.5,
             istGroesse: "frei", label: "Eigenes Maß"),
    ]
}
