// ERZEUGT VON scripts/zeichnung_swift.py. NICHT VON HAND ÄNDERN.
//
// Die Quelle ist backend/designer/bibliothek.py, durchgereicht durch
// schema.validate_play_data -- also genau das, was der Server ausliefert.
// Dazu jede Probe ein zweites Mal, gespiegelt von schema.mirror_play.
//
// Neu erzeugen:  ./scripts/zeichnung_swift.py
// Geprüft von:   backend/designer/test_zeichnung_swift.py (Gleichstand)
//                RoutetreeTests/ZeichnungTests.swift (Hin und zurück)

import Foundation

enum ZeichnungProben {

    /// Spread Mesh (Short Pass)
    static let mesh = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":22.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":35.0,"y":7.5},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":35.0,"y":2.5}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Mesh","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":22.5},{"x":38.0,"y":19.5},{"x":38.5,"y":7.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Mesh","motion_bis":0,"player":"o_z","points":[{"x":35.0,"y":2.5},{"x":38.0,"y":5.5},{"x":38.5,"y":17.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Corner","motion_bis":0,"player":"o_y","points":[{"x":35.0,"y":7.5},{"x":43.0,"y":7.5},{"x":51.0,"y":2.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Check","motion_bis":0,"player":"o_c","points":[{"x":35.0,"y":12.5},{"x":39.0,"y":10.5}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Trips Right Flood (Deep Pass)
    static let flood = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":2.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":35.0,"y":6.0},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":34.0,"y":9.5}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Go","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":2.5},{"x":53.0,"y":2.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Out","motion_bis":0,"player":"o_y","points":[{"x":35.0,"y":6.0},{"x":43.0,"y":6.0},{"x":43.5,"y":1.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Flat","motion_bis":0,"player":"o_z","points":[{"x":34.0,"y":9.5},{"x":35.5,"y":2.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"block","label":"Screen","motion_bis":0,"player":"o_c","points":[{"x":35.0,"y":12.5},{"x":36.0,"y":15.5}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Twins Right Slant & Flat (Short Pass)
    static let slantflat = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":2.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":35.0,"y":6.5},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":35.0,"y":22.0}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Slant","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":2.5},{"x":37.5,"y":5.5},{"x":42.0,"y":10.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Flat","motion_bis":0,"player":"o_y","points":[{"x":35.0,"y":6.5},{"x":37.0,"y":1.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Go","motion_bis":0,"player":"o_z","points":[{"x":35.0,"y":22.0},{"x":51.0,"y":22.0}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Spread Verticals (Deep Pass)
    static let verticals = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":22.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":35.0,"y":7.5},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":35.0,"y":2.5}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Go","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":22.5},{"x":55.0,"y":22.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Seam","motion_bis":0,"player":"o_y","points":[{"x":35.0,"y":7.5},{"x":41.0,"y":9.0},{"x":53.0,"y":9.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Go","motion_bis":0,"player":"o_z","points":[{"x":35.0,"y":2.5},{"x":55.0,"y":2.5}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Bunch Right Smash (Red Zone)
    static let smash = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":3.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":33.5,"y":6.0},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":32.5,"y":4.0}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Hitch","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":3.5},{"x":40.0,"y":3.5},{"x":39.5,"y":2.0}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Corner","motion_bis":0,"player":"o_y","points":[{"x":33.5,"y":6.0},{"x":40.5,"y":7.0},{"x":47.5,"y":1.0}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Flat","motion_bis":0,"player":"o_z","points":[{"x":32.5,"y":4.0},{"x":34.0,"y":0.5}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Twins Right Stick (Short Pass)
    static let stick = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":2.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":35.0,"y":6.5},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":35.0,"y":22.0}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Stick","motion_bis":0,"player":"o_y","points":[{"x":35.0,"y":6.5},{"x":40.0,"y":6.5},{"x":40.0,"y":3.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Go","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":2.5},{"x":52.0,"y":2.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Drag","motion_bis":0,"player":"o_z","points":[{"x":35.0,"y":22.0},{"x":39.0,"y":17.0},{"x":39.5,"y":9.0}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Spread Levels (Short Pass)
    static let levels = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":22.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":35.0,"y":7.5},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":35.0,"y":2.5}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Under","motion_bis":0,"player":"o_z","points":[{"x":35.0,"y":2.5},{"x":38.0,"y":6.5},{"x":38.5,"y":12.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Dig","motion_bis":0,"player":"o_y","points":[{"x":35.0,"y":7.5},{"x":43.0,"y":7.5},{"x":43.5,"y":14.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Go","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":22.5},{"x":53.0,"y":22.5}],"speed":1.0,"zonenform":"linie"}]}"#

    /// I-Form Wheel (Trick)
    static let wheel = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":32.0,"y":12.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":28.5,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":3.0},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":35.0,"y":22.0}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Wheel","motion_bis":0,"player":"o_y","points":[{"x":28.5,"y":12.5},{"x":29.5,"y":5.5},{"x":35.5,"y":3.5},{"x":45.5,"y":3.0}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Drag","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":3.0},{"x":39.0,"y":7.0},{"x":39.5,"y":14.0}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Post","motion_bis":0,"player":"o_z","points":[{"x":35.0,"y":22.0},{"x":44.0,"y":22.0},{"x":52.0,"y":17.0}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Deuce Screen Right (Trick)
    static let screen = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":31.0,"y":12.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":29.5,"y":15.5},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":29.5,"y":9.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":2.5}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Screen","motion_bis":0,"player":"o_z","points":[{"x":29.5,"y":9.5},{"x":30.0,"y":4.5},{"x":31.5,"y":1.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"block","label":"Screen","motion_bis":0,"player":"o_y","points":[{"x":29.5,"y":15.5},{"x":31.0,"y":8.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Clear","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":2.5},{"x":49.0,"y":4.5}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Trips Right Snag (Red Zone)
    static let snag = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":2.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":35.0,"y":6.0},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":34.0,"y":9.5}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Snag","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":2.5},{"x":39.5,"y":5.5},{"x":39.5,"y":6.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Corner","motion_bis":0,"player":"o_y","points":[{"x":35.0,"y":6.0},{"x":41.0,"y":6.0},{"x":48.0,"y":2.0}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Flat","motion_bis":0,"player":"o_z","points":[{"x":34.0,"y":9.5},{"x":36.0,"y":5.0}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Spread Mesh, gespiegelt von schema.mirror_play
    static let meshGespiegelt = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":2.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":35.0,"y":17.5},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":35.0,"y":22.5}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Mesh","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":2.5},{"x":38.0,"y":5.5},{"x":38.5,"y":17.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Mesh","motion_bis":0,"player":"o_z","points":[{"x":35.0,"y":22.5},{"x":38.0,"y":19.5},{"x":38.5,"y":7.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Corner","motion_bis":0,"player":"o_y","points":[{"x":35.0,"y":17.5},{"x":43.0,"y":17.5},{"x":51.0,"y":22.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Check","motion_bis":0,"player":"o_c","points":[{"x":35.0,"y":12.5},{"x":39.0,"y":14.5}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Trips Right Flood, gespiegelt von schema.mirror_play
    static let floodGespiegelt = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":22.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":35.0,"y":19.0},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":34.0,"y":15.5}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Go","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":22.5},{"x":53.0,"y":22.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Out","motion_bis":0,"player":"o_y","points":[{"x":35.0,"y":19.0},{"x":43.0,"y":19.0},{"x":43.5,"y":23.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Flat","motion_bis":0,"player":"o_z","points":[{"x":34.0,"y":15.5},{"x":35.5,"y":22.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"block","label":"Screen","motion_bis":0,"player":"o_c","points":[{"x":35.0,"y":12.5},{"x":36.0,"y":9.5}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Twins Right Slant & Flat, gespiegelt von schema.mirror_play
    static let slantflatGespiegelt = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":22.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":35.0,"y":18.5},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":35.0,"y":3.0}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Slant","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":22.5},{"x":37.5,"y":19.5},{"x":42.0,"y":14.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Flat","motion_bis":0,"player":"o_y","points":[{"x":35.0,"y":18.5},{"x":37.0,"y":23.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Go","motion_bis":0,"player":"o_z","points":[{"x":35.0,"y":3.0},{"x":51.0,"y":3.0}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Spread Verticals, gespiegelt von schema.mirror_play
    static let verticalsGespiegelt = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":2.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":35.0,"y":17.5},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":35.0,"y":22.5}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Go","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":2.5},{"x":55.0,"y":2.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Seam","motion_bis":0,"player":"o_y","points":[{"x":35.0,"y":17.5},{"x":41.0,"y":16.0},{"x":53.0,"y":15.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Go","motion_bis":0,"player":"o_z","points":[{"x":35.0,"y":22.5},{"x":55.0,"y":22.5}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Bunch Right Smash, gespiegelt von schema.mirror_play
    static let smashGespiegelt = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":21.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":33.5,"y":19.0},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":32.5,"y":21.0}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Hitch","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":21.5},{"x":40.0,"y":21.5},{"x":39.5,"y":23.0}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Corner","motion_bis":0,"player":"o_y","points":[{"x":33.5,"y":19.0},{"x":40.5,"y":18.0},{"x":47.5,"y":24.0}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Flat","motion_bis":0,"player":"o_z","points":[{"x":32.5,"y":21.0},{"x":34.0,"y":24.5}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Twins Right Stick, gespiegelt von schema.mirror_play
    static let stickGespiegelt = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":22.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":35.0,"y":18.5},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":35.0,"y":3.0}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Stick","motion_bis":0,"player":"o_y","points":[{"x":35.0,"y":18.5},{"x":40.0,"y":18.5},{"x":40.0,"y":21.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Go","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":22.5},{"x":52.0,"y":22.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Drag","motion_bis":0,"player":"o_z","points":[{"x":35.0,"y":3.0},{"x":39.0,"y":8.0},{"x":39.5,"y":16.0}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Spread Levels, gespiegelt von schema.mirror_play
    static let levelsGespiegelt = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":2.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":35.0,"y":17.5},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":35.0,"y":22.5}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Under","motion_bis":0,"player":"o_z","points":[{"x":35.0,"y":22.5},{"x":38.0,"y":18.5},{"x":38.5,"y":12.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Dig","motion_bis":0,"player":"o_y","points":[{"x":35.0,"y":17.5},{"x":43.0,"y":17.5},{"x":43.5,"y":10.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Go","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":2.5},{"x":53.0,"y":2.5}],"speed":1.0,"zonenform":"linie"}]}"#

    /// I-Form Wheel, gespiegelt von schema.mirror_play
    static let wheelGespiegelt = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":32.0,"y":12.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":28.5,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":22.0},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":35.0,"y":3.0}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Wheel","motion_bis":0,"player":"o_y","points":[{"x":28.5,"y":12.5},{"x":29.5,"y":19.5},{"x":35.5,"y":21.5},{"x":45.5,"y":22.0}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Drag","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":22.0},{"x":39.0,"y":18.0},{"x":39.5,"y":11.0}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Post","motion_bis":0,"player":"o_z","points":[{"x":35.0,"y":3.0},{"x":44.0,"y":3.0},{"x":52.0,"y":8.0}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Deuce Screen Right, gespiegelt von schema.mirror_play
    static let screenGespiegelt = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":31.0,"y":12.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":29.5,"y":9.5},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":29.5,"y":15.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":22.5}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Screen","motion_bis":0,"player":"o_z","points":[{"x":29.5,"y":15.5},{"x":30.0,"y":20.5},{"x":31.5,"y":23.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"block","label":"Screen","motion_bis":0,"player":"o_y","points":[{"x":29.5,"y":9.5},{"x":31.0,"y":16.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Clear","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":22.5},{"x":49.0,"y":20.5}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Trips Right Snag, gespiegelt von schema.mirror_play
    static let snagGespiegelt = #"{"players":[{"color":"","id":"o_c","label":"C","note":"","role":"C","side":"off","x":35.0,"y":12.5},{"color":"","id":"o_qb","label":"Q","note":"","role":"QB","side":"off","x":30.0,"y":12.5},{"color":"","id":"o_x","label":"X","note":"","role":"X","side":"off","x":35.0,"y":22.5},{"color":"","id":"o_y","label":"Y","note":"","role":"Y","side":"off","x":35.0,"y":19.0},{"color":"","id":"o_z","label":"Z","note":"","role":"Z","side":"off","x":34.0,"y":15.5}],"routes":[{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Snag","motion_bis":0,"player":"o_x","points":[{"x":35.0,"y":22.5},{"x":39.5,"y":19.5},{"x":39.5,"y":18.5}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Corner","motion_bis":0,"player":"o_y","points":[{"x":35.0,"y":19.0},{"x":41.0,"y":19.0},{"x":48.0,"y":23.0}],"speed":1.0,"zonenform":"linie"},{"curve":false,"delay":0.0,"end":"arrow","kind":"route","label":"Flat","motion_bis":0,"player":"o_z","points":[{"x":34.0,"y":15.5},{"x":36.0,"y":20.0}],"speed":1.0,"zonenform":"linie"}]}"#

    /// Alle Proben mit ihrem Schlüssel, für den Durchlauf im Test.
    static let alle: [(schluessel: String, json: String)] = [
        ("mesh", mesh),
        ("flood", flood),
        ("slantflat", slantflat),
        ("verticals", verticals),
        ("smash", smash),
        ("stick", stick),
        ("levels", levels),
        ("wheel", wheel),
        ("screen", screen),
        ("snag", snag)
    ]

    /// Jede Probe mit ihrem gespiegelten Gegenstück, für `SpiegelungTests`.
    static let spiegelpaare: [(schluessel: String, json: String,
                               gespiegelt: String)] = [
        ("mesh", mesh, meshGespiegelt),
        ("flood", flood, floodGespiegelt),
        ("slantflat", slantflat, slantflatGespiegelt),
        ("verticals", verticals, verticalsGespiegelt),
        ("smash", smash, smashGespiegelt),
        ("stick", stick, stickGespiegelt),
        ("levels", levels, levelsGespiegelt),
        ("wheel", wheel, wheelGespiegelt),
        ("screen", screen, screenGespiegelt),
        ("snag", snag, snagGespiegelt)
    ]
}
